--- #Tarefas para adicionar um novo usu치rio e conceder acesso ssh ao usu치rio
- name: Adciona novo usu치rio
  user:
    name: "{{ user_name }}"
    comment: "{{ user_des }}"
    shell: /bin/bash
  tags:
    - add

- name: Concede acesso SSH ao usu치rio
  authorized_key:
    user: "{{ user_name }}"
    state: present
    key: "{{ lookup('file', '../../../keys/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - grant