--- #tarefas para remover o usu치rio e revogar o acesso ssh do usu치rio
- name: Revoga acesso SSH do usu치rio
  authorized_key:
    user: "{{ user_name }}"
    state: absent
    key: "{{ lookup('file', '../../../keys/{{ user_name }}/id_rsa.pub') }}"
  tags:
    - revoke

- name: Remove o usu치rio
  user:
    name: "{{ user_name }}"
    state: absent
    remove: yes
  tags:
    - remove
